### ISSUE TITLE
Replace geopoint boolean with bounding box in schema

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#1]
If dataset contains coordinates, they are indexed as geopoint and a boolean geopoint = true is set at the schema root.
We should replace this boolean with a bounding box : we can know that a dataset is geolocalized by testing the existence of this bbox property. And this property will be usefull to set a ma on the dataset.

The values in this propery could be used instead of the default bbox when no one is provided in the geo_agg route.

**Comment by albanm** [comment]
Done.
