### ISSUE TITLE
Reload data after enrichment

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#16]
When enrichment is done, you have to do F5 to see the results. We should automatically reload data.

**Comment by albanm** [comment]
I worked on a few things regarding auto reloading of data:

  - when importing a dataset, the user is redirected to its page
  - message from last event in journal is also shown on description (real time)
  - when dataset receives finalize-end event (i.e. each time it is processed in any manner) metadata and data are reloaded
