### ISSUE TITLE
Improved feedback with wrongly formated datasets

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#25]
* When a line has more items than in header (i.e more fields delimiters), indexing fails but error is not clear.
 * When a datasets has blank lines, there is now error, but this raises errors when adding extensions. We should ignore these blank lines.
 * Perhaps improve extensions by ignoring rows that do not have required concepts for the extension applied

**Comment by albanm** [comment]
Maybe not perfect, but I pushed a few improvements on this topic.

Indexing failures are better displayed, and empty queries are not sent for extension.
