### ISSUE TITLE
Snack bar duration should be reduced, and sometimes should not appear

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#26]
We should reduce snackbar duration, and close snackbar before raising another notification.

There is also a problem when importing large datasets, going to another browser tab and going back on tab with import : the snackbar appears but import is not finished (progress bar not completed)

**Comment by albanm** [comment]
Did not reproduce the bug.

Some improvements on notification:
  - switched to event bus logic that better matches the purpose than vuex
  - shorter durations
  - always hide and show the notification even if the message is the same
  - no conflict of error and info notifications
