### ISSUE TITLE
API endpoint to get permissions for a configured application

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#28]
We currently have an API endpoint to read / save configuration of applications. But we have no way to know if user has rights to write this config.

Use case : Be able to hide config button on applications toolbar if user can't write config file.

**Comment by albanm** [comment]
Same thing for almost all resources and operations.

We need a "can i ?" route with resource type, resource id, operation id.

**Comment by nicolas-bonnel** [comment]
Resources now carry permissions of the requesting user in a `userPermissions` property. An `x-application-url` header replace `x-config-url` so that the configured application can query the resource to have the user permissions.
