### ISSUE TITLE
Prefill new application from URL query params

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#33]
New feature :
On the application list screen, when the URL query parameter `add-applicationl` is set and the value of this parameter matches the url of an application in the config, the `add new application` workflow is already open and set to the 2nd stage.

**Comment by albanm** [comment]
Done in data-fair both for applications and remote-services, added a query parameter "import".

For example : /remote-services?import=https%3A%2F%2Fkoumoul.com%2Fs%2Fsirene%2Fapi-docs.json

Dit not go through the applications to use this yet.
