### ISSUE TITLE
user friendly ids

### ISSUE THREAD

**Issue by albanm** [koumoul-dev/data-fair#4]
Datasets and remote services urls are manipulated by developpers and applications urls by users.

Having meaningful urls would be better, and in each case we can have a good base identifier (dataset / filename, remote service / api id, application / application id). We should use increments based on these.

Already done in datasets (see server/utils/files.js).

**Comment by nicolas-bonnel** [comment]
Now using slug library for datasets ids. I also used that lib for remote services (but i don't think its really necessary). For applications, I took last part of the URL as there is no id in HTLM files and title is not mandatory.
