### ISSUE TITLE
Ability to generate API keys for permissions

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#44]
We should be able to access DataFair API endpoints using API keys.

We could add a new type in permissions schema (api-key). The id would be the API key itself and the name the description of the API key. Like permissions on users, permissions on API keys would not set roles.

One question remain : should API keys be local for each resource or more global ? Global API keys could be stored in settings of the resource owner.

**Comment by albanm** [comment]
An API key system was implemented with global scopes in an organization. If we really need finer controls, we will see later.
