### ISSUE TITLE
Browser crash with a dataset

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#47]
Uploading [this dataset](http://data.iledefrance.fr/explore/dataset/les-aeroports-dile-de-france/download?format=csv) and settings columns to latitude / longitude and geojson shape make the browser crash after using the map few seconds.

Also some shapes do not appear on the map.

I haven't check if the dataset format is correct but the app should at least not crash.

**Comment by albanm** [comment]
Fixed at the same time as #48
