### ISSUE TITLE
Render application button, going back button, menu button only display disconnect.

### ISSUE THREAD

**Issue by Bloumba** [koumoul-dev/data-fair#57]
The render application button should be more explicit and not the K.There also should be a button to go back to the previous pannel. The menu only show a disconnection option.
![render](https://user-images.githubusercontent.com/28899086/39702509-6346a40c-5205-11e8-9178-d4feebaf7962.png)
![menu](https://user-images.githubusercontent.com/28899086/39702513-66a37fee-5205-11e8-870f-866608001d3b.png)

**Comment by nicolas-bonnel** [comment]
This is an issue in a data-fair application, not data-fair itself.
