### ISSUE TITLE
Too much panels to make a configuration

### ISSUE THREAD

**Issue by Bloumba** [koumoul-dev/data-fair#60]
Would be better to have less panels to make a full configuration of the data and the application. It feels like it's the same panels. 
![samepanel](https://user-images.githubusercontent.com/28899086/39703414-4523f8e6-5208-11e8-87f8-9c02e7b44acc.png)
![samepanel-](https://user-images.githubusercontent.com/28899086/39703422-48af4c18-5208-11e8-8b8d-6573ef2a8ae0.png)

**Comment by nicolas-bonnel** [comment]
This is an issue in a data-fair application, not data-fair itself.
