### ISSUE TITLE
Owner applications

### ISSUE THREAD

**Issue by BalamSal** [koumoul-dev/data-fair#66]
Owner applications (privates and public) should be displayed on the "configuration d'applications" section.
Only private applications are displayed at the moment. The user has to click on "Voir les applications publiques des autres..." to see his own public applications.

**Comment by nicolas-bonnel** [comment]
Lists (datasets, remote-services and applications) now show only elements owned by the user. The toggle allow to see others elements (public ones or privates ones if the user has some permissions on them)
