### ISSUE TITLE
Download enriched data

### ISSUE THREAD

**Issue by BalamSal** [koumoul-dev/data-fair#70]
Trying to download the enriched file can lead to a bad gateway page. Most of the times the download will work, but sometimes the user get a bad gateway page. 

Happens with this dataset : https://koumoul.com/s/data-fair/dataset/companies_france_export_lille/description

**Comment by albanm** [comment]
Fixed and deployed in production on koumoul.com.

But download is very slow. Maybe we should add an issue to try to optimize that.

**Comment by BalamSal** [comment]
The link lead to an enriched dataset, but the wording to describe the enriched data is not clear. For the longitud I have _ext_geocoder-koumoul13_postCoords.lon as description and for latitud _ext_geocoder-koumoul13_postCoords.lat as "libellé".

**Comment by albanm** [comment]
Juste released and deployed a version where fields' titles are used instead of raw keys.

**Comment by BalamSal** [comment]
The link to download the enrichied data and the wording to describe it are fixed .
