### ISSUE TITLE
Download filtered data

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#72]
Sometimes, we need to filter a dataset and work on a subset of those filtered data. To make filtering easier, we need some facets on data (if number of different items is low) and an API endpoint (we could update existing ones).

For the UI part, I'm not sure DataFair should handle it, perhaps in a dedicated application (like portail-thematique) ?

**Comment by albanm** [comment]
replaced by https://github.com/koumoul-dev/data-fair/issues/93 and https://github.com/koumoul-dev/data-fair/issues/94
