### ISSUE TITLE
Consomation when 2 enrichements are available

### ISSUE THREAD

**Issue by BalamSal** [koumoul-dev/data-fair#75]
When the geocoding and the entreprise are available and both are checked, there is a different comportement on the consomation on unchecking each enrichment.

Happens with this data set :
https://koumoul.com/s/data-fair/dataset/companies_france_export_lille2/description

When unchecking the geocoding, the entreprise enrichment is executed and the consomation of "données d'entreprises" goes up.

**Comment by nicolas-bonnel** [comment]
Unchecking an enrichment should not consume external APIs for the remaining checked enrichments
