### ISSUE TITLE
"Données des entreprises" service importation

### ISSUE THREAD

**Issue by BalamSal** [koumoul-dev/data-fair#81]
- The waiting time on this mesage is longer than usual : Ce service permet de récupérer les informations des entreprises de France ... The waiting time should be reduce if possible. 
- Clicking on the documentation link, the user is directed to the documentation but loose all progress on the import of the service. Clicking on the documentation link should open a new page with the documentation info.
- On the last stage of the import, the user got the feeling that the "Lancer l'import" button do nothing. Maybe add a pogress bar. The user can click many times on the button, he can make a loop and add infinite service with the button. On 10 clicks try, 9 services were added, I could have clicked many more times. The user should not be able to click more than one on the button "Lancer l'import". On the 10 try, the user get a huge error massage and he can not close it. Escape key should be able to remove the error message if the user can't acces to the cross to close the message. 
[erreur Lancer.txt](https://github.com/koumoul-dev/data-fair/files/2016067/erreur.Lancer.txt)

If the user only clicks 3 times he will get this message : Erreur pendant l'import du service

E11000 duplicate key error collection: data-fair-production.remote-services index: id_1 dup key: { : "sirene-koumoul17" }

**Comment by albanm** [comment]
No longer relevant I think.
